language: go

before_script:
- curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.10.2

script:
- cd hello && go build && ./hello
- golangci-lint run